# Build numbering format
name: frontend_$(working-dir)_cd_$(BuildID)

trigger:
  tags:
    include:
      - 'v*'
  branches:
    exclude:
      - '*'
  paths:
    include:
      - '$(working-dir)/*'
    exclude:
      - '$(working-dir)/templates/*'
      - '$(working-dir)/azure-pipelines.yml'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: working-dir
    value: 'app1'
  - name: AWS_ACCOUNT_ID
    value: 557410075654
  - name: AWS_REGION
    value: us-west-2
  - name: DOCKERFILE_PATH
    value: $(working-dir)/Dockerfile
  - name: test-env
    value: test
  - name: TEST_APP_NAME
    value: $(test-env)-frontend-$(working-dir)-repo
  - name: TEST_FARGATE_CLUSTER_ARN
    value: arn:aws:ecs:$(AWS_REGION):$(AWS_ACCOUNT_ID):cluster/$(test-env)-ecs-cluster
  - name: TEST_SERVICE_NAME
    value: ecs-$(test-env)-frontend-$(working-dir)-service
  - name: TEST_ECR_REPOSITORY
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(TEST_APP_NAME)
  - name: prod-env
    value: prod
  - name: PROD_APP_NAME
    value: $(prod-env)-frontend-$(working-dir)-repo
  - name: PROD_FARGATE_CLUSTER_ARN
    value: arn:aws:ecs:$(AWS_REGION):$(AWS_ACCOUNT_ID):cluster/$(prod-env)-ecs-cluster
  - name: PROD_SERVICE_NAME
    value: ecs-$(prod-env)-frontend-$(working-dir)-service
  - name: PROD_ECR_REPOSITORY
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(PROD_APP_NAME)
  - name: TAG
    value: $(Build.SourceBranchName)

stages:
  - stage: app1_install
    displayName: 'Install App1'
    jobs:
      - job: check_folder_changed
        displayName: 'Check Folder Changed?'
        condition: eq(variables['Build.Reason'], 'IndividualCI')
        steps:
          - checkout: self
            fetchDepth: 0
          - script: |
              if [ "$(Build.Reason)" == "IndividualCI" ]; then
                commit=$(git rev-parse HEAD)
                changedFiles=$(git diff --name-only HEAD HEAD^)
              fi

              if [[ "$changedFiles" == *"$(working-dir)"* ]]; then
                echo "Changes detected in $(working-dir)"
                echo "##vso[task.setvariable variable=has_changed;isOutput=true;]true"
              else
                echo "No changes detected in $(working-dir) "
              fi
            name: folder_changed
      - template: ../templates/run-cd.yml
